// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_LSDCARD = NULL;
lv_obj_t * ui_TSDCARD = NULL;
lv_obj_t * ui_LBAT = NULL;
lv_obj_t * ui_TBAT = NULL;
lv_obj_t * ui_IMGBAT = NULL;
lv_obj_t * ui_LWIFI = NULL;
lv_obj_t * ui_TWIFI = NULL;
lv_obj_t * ui_LBLE = NULL;
lv_obj_t * ui_TBLE = NULL;
lv_obj_t * ui_LMAG = NULL;
lv_obj_t * ui_TMAG = NULL;
lv_obj_t * ui_LRTC = NULL;
lv_obj_t * ui_TRTC = NULL;
lv_obj_t * ui_LGPS = NULL;
lv_obj_t * ui_TGPS = NULL;
lv_obj_t * ui_BCODEC = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_BGPIO47 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_BGPIO17 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_BGPIO16 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_BGPIO15 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_BGPIO14 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_spac = NULL;
lv_obj_t * ui_BTOUCH = NULL;
// event funtions
void ui_event_Container2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_indev_t * indev = lv_event_get_indev(e);
    lv_point_t touch_pos;
    lv_indev_get_point(indev, &touch_pos);  // Get current touch coordinates

    /* The rectangle of the container on the screen (coords is the screen coordinate system) */
    lv_area_t cont_coords;
    lv_obj_get_coords(ui_Container2, &cont_coords); // cont_coords.x1/y1 is the top-left screen coordinate.

    /* Get the scroll offset of the container (the offset of the content's origin relative to the visible area) */
    lv_coord_t scroll_x = 0;
    lv_coord_t scroll_y = 0;
    scroll_x = lv_obj_get_scroll_x(ui_Container2);
    scroll_y = lv_obj_get_scroll_y(ui_Container2);

    /* Calculate the container's internal coordinates (local) */
    lv_point_t local_p;
    local_p.x = touch_pos.x - cont_coords.x1 + scroll_x;
    local_p.y = touch_pos.y - cont_coords.y1 + scroll_y;

    if(event_code == LV_EVENT_PRESSED || event_code == LV_EVENT_PRESSING) {
        _ui_flag_modify(ui_BTOUCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        lv_obj_set_pos(ui_BTOUCH, local_p.x - 10, local_p.y - 10);  // Subtracting 10 is to center the point.
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_BTOUCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_BCODEC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Begin_Rec(e);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SET_BLPWM(e);
    }
}

void ui_event_BGPIO47(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GPIO47CALL(e);
    }
}

void ui_event_BGPIO17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GPIO17CALL(e);
    }
}

void ui_event_BGPIO16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GPIO16CALL(e);
    }
}

void ui_event_BGPIO15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GPIO15CALL(e);
    }
}

void ui_event_BGPIO14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GPIO14CALL(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_test3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, lv_pct(100));
    // lv_obj_add_flag(ui_Container2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags

    ui_LSDCARD = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LSDCARD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LSDCARD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LSDCARD, -100);
    lv_obj_set_y(ui_LSDCARD, -175);
    lv_obj_set_align(ui_LSDCARD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LSDCARD, "SD CARD");

    ui_TSDCARD = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TSDCARD, 250);
    lv_obj_set_height(ui_TSDCARD, 45);
    lv_obj_set_x(ui_TSDCARD, -10);
    lv_obj_set_y(ui_TSDCARD, -135);
    lv_obj_set_align(ui_TSDCARD, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TSDCARD, "Memory...");
    lv_obj_remove_flag(ui_TSDCARD, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LBAT = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LBAT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LBAT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LBAT, -120);
    lv_obj_set_y(ui_LBAT, -95);
    lv_obj_set_align(ui_LBAT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LBAT, "BAT");

    ui_TBAT = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TBAT, 250);
    lv_obj_set_height(ui_TBAT, 45);
    lv_obj_set_x(ui_TBAT, -10);
    lv_obj_set_y(ui_TBAT, -55);
    lv_obj_set_align(ui_TBAT, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TBAT, "4.2V...");
    lv_obj_remove_flag(ui_TBAT, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_IMGBAT = lv_obj_create(ui_TBAT);
    lv_obj_set_width(ui_IMGBAT, lv_pct(10));
    lv_obj_set_height(ui_IMGBAT, lv_pct(100));
    lv_obj_set_align(ui_IMGBAT, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_IMGBAT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IMGBAT, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMGBAT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LWIFI = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LWIFI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LWIFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LWIFI, -120);
    lv_obj_set_y(ui_LWIFI, -15);
    lv_obj_set_align(ui_LWIFI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LWIFI, "WIFI");

    ui_TWIFI = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TWIFI, 250);
    lv_obj_set_height(ui_TWIFI, 45);
    lv_obj_set_x(ui_TWIFI, -10);
    lv_obj_set_y(ui_TWIFI, 25);
    lv_obj_set_align(ui_TWIFI, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TWIFI, "number...");
    lv_obj_remove_flag(ui_TWIFI, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    // ui_LBLE = lv_label_create(ui_Container2);
    // lv_obj_set_width(ui_LBLE, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_LBLE, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_LBLE, 30);
    // lv_obj_set_y(ui_LBLE, -15);
    // lv_obj_set_align(ui_LBLE, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_LBLE, "BLE");

    // ui_TBLE = lv_textarea_create(ui_Container2);
    // lv_obj_set_width(ui_TBLE, 100);
    // lv_obj_set_height(ui_TBLE, 45);
    // lv_obj_set_x(ui_TBLE, 65);
    // lv_obj_set_y(ui_TBLE, 25);
    // lv_obj_set_align(ui_TBLE, LV_ALIGN_CENTER);
    // lv_textarea_set_placeholder_text(ui_TBLE, "number...");
    // lv_obj_remove_flag(ui_TBLE, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LMAG = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LMAG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LMAG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LMAG, -65);
    lv_obj_set_y(ui_LMAG, 65);
    lv_obj_set_align(ui_LMAG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LMAG, "Angular deflection");

    ui_TMAG = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TMAG, 250);
    lv_obj_set_height(ui_TMAG, 45);
    lv_obj_set_x(ui_TMAG, -10);
    lv_obj_set_y(ui_TMAG, 105);
    lv_obj_set_align(ui_TMAG, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TMAG, "X:0 Y:0 Z:0");
    lv_obj_remove_flag(ui_TMAG, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LRTC = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LRTC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LRTC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LRTC, -100);
    lv_obj_set_y(ui_LRTC, 145);
    lv_obj_set_align(ui_LRTC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LRTC, "RTC Time");

    ui_TRTC = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TRTC, 250);
    lv_obj_set_height(ui_TRTC, 45);
    lv_obj_set_x(ui_TRTC, -10);
    lv_obj_set_y(ui_TRTC, 185);
    lv_obj_set_align(ui_TRTC, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TRTC, "2025.10.23 4 14:53:05");
    lv_obj_remove_flag(ui_TRTC, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LGPS = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LGPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LGPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LGPS, -95);
    lv_obj_set_y(ui_LGPS, 225);
    lv_obj_set_align(ui_LGPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LGPS, "GPS LC76G");

    ui_TGPS = lv_textarea_create(ui_Container2);
    lv_obj_set_width(ui_TGPS, 250);
    lv_obj_set_height(ui_TGPS, 45);
    lv_obj_set_x(ui_TGPS, -10);
    lv_obj_set_y(ui_TGPS, 265);
    lv_obj_set_align(ui_TGPS, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TGPS, "GPS Init Fail");
    lv_obj_remove_flag(ui_TGPS, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_BCODEC = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_BCODEC, 250);
    lv_obj_set_height(ui_BCODEC, 50);
    lv_obj_set_x(ui_BCODEC, -10);
    lv_obj_set_y(ui_BCODEC, 325);
    lv_obj_set_align(ui_BCODEC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BCODEC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BCODEC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_BCODEC);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SPK MIC TEST");

    ui_Slider1 = lv_slider_create(ui_Container2);
    lv_slider_set_range(ui_Slider1, 0, 100);
    lv_slider_set_value(ui_Slider1, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 200);
    lv_obj_set_height(ui_Slider1, 30);
    lv_obj_set_x(ui_Slider1, -10);
    lv_obj_set_y(ui_Slider1, 385);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_BGPIO47 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_BGPIO47, 40);
    lv_obj_set_height(ui_BGPIO47, 50);
    lv_obj_set_x(ui_BGPIO47, -110);
    lv_obj_set_y(ui_BGPIO47, 440);
    lv_obj_set_align(ui_BGPIO47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGPIO47, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BGPIO47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_BGPIO47);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "47");

    ui_BGPIO17 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_BGPIO17, 40);
    lv_obj_set_height(ui_BGPIO17, 50);
    lv_obj_set_x(ui_BGPIO17, -60);
    lv_obj_set_y(ui_BGPIO17, 440);
    lv_obj_set_align(ui_BGPIO17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGPIO17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BGPIO17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_BGPIO17);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "17");

    ui_BGPIO16 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_BGPIO16, 40);
    lv_obj_set_height(ui_BGPIO16, 50);
    lv_obj_set_x(ui_BGPIO16, -10);
    lv_obj_set_y(ui_BGPIO16, 440);
    lv_obj_set_align(ui_BGPIO16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGPIO16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BGPIO16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_BGPIO16);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "16");

    ui_BGPIO15 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_BGPIO15, 40);
    lv_obj_set_height(ui_BGPIO15, 50);
    lv_obj_set_x(ui_BGPIO15, 40);
    lv_obj_set_y(ui_BGPIO15, 440);
    lv_obj_set_align(ui_BGPIO15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGPIO15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BGPIO15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_BGPIO15);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "15");

    ui_BGPIO14 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_BGPIO14, 40);
    lv_obj_set_height(ui_BGPIO14, 50);
    lv_obj_set_x(ui_BGPIO14, 90);
    lv_obj_set_y(ui_BGPIO14, 440);
    lv_obj_set_align(ui_BGPIO14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGPIO14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BGPIO14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_BGPIO14);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "14");

    ui_spac = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_spac, 100);
    lv_obj_set_height(ui_spac, 50);
    lv_obj_set_x(ui_spac, 0);
    lv_obj_set_y(ui_spac, 480);
    lv_obj_set_align(ui_spac, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_spac, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_spac, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_spac, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_spac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_spac, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTOUCH = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_BTOUCH, 20);
    lv_obj_set_height(ui_BTOUCH, 20);
    lv_obj_add_flag(ui_BTOUCH, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTOUCH, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTOUCH, lv_color_hex(0xFF00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTOUCH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BCODEC, ui_event_BCODEC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BGPIO47, ui_event_BGPIO47, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BGPIO17, ui_event_BGPIO17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BGPIO16, ui_event_BGPIO16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BGPIO15, ui_event_BGPIO15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BGPIO14, ui_event_BGPIO14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container2, ui_event_Container2, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container2 = NULL;
    ui_LSDCARD = NULL;
    ui_TSDCARD = NULL;
    ui_LBAT = NULL;
    ui_TBAT = NULL;
    ui_IMGBAT = NULL;
    ui_LWIFI = NULL;
    ui_TWIFI = NULL;
    ui_LBLE = NULL;
    ui_TBLE = NULL;
    ui_LMAG = NULL;
    ui_TMAG = NULL;
    ui_LRTC = NULL;
    ui_TRTC = NULL;
    ui_LGPS = NULL;
    ui_TGPS = NULL;
    ui_BCODEC = NULL;
    ui_Label6 = NULL;
    ui_Slider1 = NULL;
    ui_BGPIO47 = NULL;
    ui_Label2 = NULL;
    ui_BGPIO17 = NULL;
    ui_Label3 = NULL;
    ui_BGPIO16 = NULL;
    ui_Label4 = NULL;
    ui_BGPIO15 = NULL;
    ui_Label5 = NULL;
    ui_BGPIO14 = NULL;
    ui_Label7 = NULL;
    ui_spac = NULL;
    ui_BTOUCH = NULL;

}
