// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_LSDCARD;
extern lv_obj_t * ui_TSDCARD;
extern lv_obj_t * ui_LBAT;
extern lv_obj_t * ui_TBAT;
extern lv_obj_t * ui_IMGBAT;
extern lv_obj_t * ui_LWIFI;
extern lv_obj_t * ui_TWIFI;
extern lv_obj_t * ui_LBLE;
extern lv_obj_t * ui_TBLE;
extern lv_obj_t * ui_LMAG;
extern lv_obj_t * ui_TMAG;
extern lv_obj_t * ui_LRTC;
extern lv_obj_t * ui_TRTC;
extern lv_obj_t * ui_LGPS;
extern lv_obj_t * ui_TGPS;
extern void ui_event_BCODEC(lv_event_t * e);
extern lv_obj_t * ui_BCODEC;
extern lv_obj_t * ui_Label6;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern void ui_event_BGPIO47(lv_event_t * e);
extern lv_obj_t * ui_BGPIO47;
extern lv_obj_t * ui_Label2;
extern void ui_event_BGPIO17(lv_event_t * e);
extern lv_obj_t * ui_BGPIO17;
extern lv_obj_t * ui_Label3;
extern void ui_event_BGPIO16(lv_event_t * e);
extern lv_obj_t * ui_BGPIO16;
extern lv_obj_t * ui_Label4;
extern void ui_event_BGPIO15(lv_event_t * e);
extern lv_obj_t * ui_BGPIO15;
extern lv_obj_t * ui_Label5;
extern void ui_event_BGPIO14(lv_event_t * e);
extern lv_obj_t * ui_BGPIO14;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_spac;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

