// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

uint8_t bat_charge;
float bat_v;
bool gpio_47 = TRUE,gpio_17 = TRUE,gpio_16 = TRUE,gpio_15 = TRUE,gpio_14 = TRUE;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void example_increase_lvgl_tick(lv_timer_t * t)
{
  char buf[200]; 

  (void)t;
  memset(buf, 0, sizeof(buf));
  snprintf(buf, sizeof(buf), "%.2f mV\r\n", bat_v);
  lv_textarea_set_placeholder_text(ui_TBAT, buf);
  if (bat_charge == 0)
    lv_obj_set_style_bg_color(ui_IMGBAT, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
  else
    lv_obj_set_style_bg_color(ui_IMGBAT, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
  
  memset(buf, 0, sizeof(buf));
  snprintf(buf, sizeof(buf), "X:%.4f  Y:%.4f  Z:%.4f\r\n", qmi_data.accelX, qmi_data.accelY, qmi_data.accelZ);
  lv_textarea_set_placeholder_text(ui_TMAG, buf);
  memset(buf, 0, sizeof(buf));
  pcf85063a_datetime_to_str(buf,datetime);
  lv_textarea_set_placeholder_text(ui_TRTC, buf);
  memset(buf, 0, sizeof(buf));
  if(WIFI_NUM != 0)
  {
    snprintf(buf, sizeof(buf), "WIFI: %d",WIFI_NUM);
    lv_textarea_set_placeholder_text(ui_TWIFI, buf);
  }

  // PR_INFO("  Time (UTC):    %02d:%02d:%02d.%03d", s->utc_hour, s->utc_minute, s->utc_second, s->utc_millisecond);  
  memset(buf, 0, sizeof(buf));
  snprintf(buf, sizeof(buf), "Time (UTC):    %02d:%02d:%02d.%03d", g_state.utc_hour, g_state.utc_minute, g_state.utc_second, g_state.utc_millisecond);
  lv_textarea_set_placeholder_text(ui_TGPS, buf);
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    lv_timer_create(example_increase_lvgl_tick, 100, NULL);
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
}
