// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include "lv_vendor.h"

#include "board_com_api.h"
#include "sd.h"
#include "pcf85063a.h"
#include "qmi8658.h"
#include "lc76g.h"
#include "wifi_ble.h"
#include "mic_spk.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

extern uint8_t bat_charge;
extern float bat_v;
extern bool gpio_47,gpio_17,gpio_16,gpio_15,gpio_14;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_test2_png);    // assets/test2.png
LV_IMG_DECLARE(ui_img_test3_png);    // assets/test2.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
