// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

#include "tdl_display_manage.h"

void Begin_Rec(lv_event_t * e)
{
	(void)e;
	// Your code here
	Start_Recording = !Start_Recording;
	PR_DEBUG("Start_Recording = %d", Start_Recording);
}

void SET_BLPWM(lv_event_t * e)
{
	// Your code here
	(void)e;
	lv_vendor_disp_lock(); 
	tal_system_sleep(50);

	TDL_DISP_HANDLE_T disp_hdl = tdl_disp_find_dev(DISPLAY_NAME);
	if (NULL != disp_hdl) {
		lv_obj_t * slider = lv_event_get_target(e); // Get the slider object that triggered the event
		tdl_disp_set_brightness(disp_hdl, lv_slider_get_value(slider));
	}

	lv_vendor_disp_unlock();
}

void GPIO47CALL(lv_event_t * e)
{
	(void)e;
	gpio_47 = !gpio_47;
	dev_digital_write(EXAMPLE_GPIO_47_PIN, gpio_47);
}

void GPIO17CALL(lv_event_t * e)
{
	(void)e;
	gpio_17 = !gpio_17;
	dev_digital_write(EXAMPLE_GPIO_17_PIN, gpio_17);
}

void GPIO16CALL(lv_event_t * e)
{
	(void)e;
	gpio_16 = !gpio_16;
	dev_digital_write(EXAMPLE_GPIO_16_PIN, gpio_16);
}

void GPIO15CALL(lv_event_t * e)
{
	(void)e;
	gpio_15 = !gpio_15;
	dev_digital_write(EXAMPLE_GPIO_15_PIN, gpio_15);
}

void GPIO14CALL(lv_event_t * e)
{
	(void)e;
	gpio_14 = !gpio_14;
	dev_digital_write(EXAMPLE_GPIO_14_PIN, gpio_14);
}

