// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Begin_Rec(lv_event_t * e);
void SET_BLPWM(lv_event_t * e);
void GPIO47CALL(lv_event_t * e);
void GPIO17CALL(lv_event_t * e);
void GPIO16CALL(lv_event_t * e);
void GPIO15CALL(lv_event_t * e);
void GPIO14CALL(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
